### ISSUE TITLE
Newly created ChromaDB collection is missing collectionId and failing on insert

### ISSUE THREAD

**Issue by novakma2** [spring-projects/spring-ai#1240]
**Bug description**
When trying to add documents to ChromaDB, client returns `404 Not Found: "{"detail":"Not Found"}"` with my multistore setup on newly added collection. 

**Environment**
Java 21; 
Springboot 3.3.2;
SpringAI 1.0.0 M1;
ChromaDB latest;

**Steps to reproduce**
Create new Springboot project with ChromaDB, create a collection using chromaAPI, and try to add a document to that collection.

**Expected behavior**
When new ChromaDB collection is created, id should be populated and all actions should be working.

**Minimal Complete Reproducible example**
In my current multi collection setup, I am creating new collection per customer and adding the client to map, as that seems to be the only way to add data to different collections.
```java
public void synchronizeCollections() {
        customerService.getCustomers().stream()
                .filter(customer -> !storeByHost.containsKey(customer.host()))
                .forEach(customer -> {
                    final var collection = chromaApi.createCollection(new ChromaApi.CreateCollectionRequest(customer.host()));
                    logger.info("Inserting new ChromaDB collection {} with name {}", collection.id(), collection.name());
                    final var store = new ChromaVectorStore(embeddingModel, chromaApi, collection.name(), true);
                    storeByHost.put(collection.name(), store);
                });
    }
```
Then when running the add for the collection of given host
```java
    public void insertToStore(String host, List<Document> documents) {
        if (!storeByHost.containsKey(host)){
            logger.error("Host is not present in ChromaDB collection, host:{}", host);
            return;
        }
        storeByHost.get(host).add(documents);
    }
```
I am receiving following exception:
```
org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: "{"detail":"Not Found"}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:112) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.ai.chroma.ChromaApi.upsertEmbeddings(ChromaApi.java:321) ~[spring-ai-chroma-store-1.0.0-M1.jar:1.0.0-M1]
	at org.springframework.ai.vectorstore.ChromaVectorStore.add(ChromaVectorStore.java:104) ~[spring-ai-chroma-store-1.0.0-M1.jar:1.0.0-M1]
	at my.site.chromadb.ChromaDbService.insertToStore(ChromaDbService.java:64) ~[classes/:na]
	at my.site.sync.SynchronizationService.sync(SynchronizationService.java:70) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
```

After doing some digging, it seems that the id of created collection is not being populated, and it throws exception on upsert embeddings where it requires the id, .. 
<img width="563" alt="Screen 2024-08-18 v 23 03 04" src="https://github.com/user-attachments/assets/9df6b08a-a77e-4ea4-a3c4-33fbd6405bdb">

The issue is then on ChromaApi.java on line 321 where its calling the endpoint with the null collection id
```java
	//
	// Chroma Collection API (https://docs.trychroma.com/js_reference/Collection)
	//

	public void upsertEmbeddings(String collectionId, AddEmbeddingsRequest embedding) {

		this.restTemplate
			.exchange(this.baseUrl + "/api/v1/collections/{collection_id}/upsert", HttpMethod.POST,
					this.getHttpEntityFor(embedding), Boolean.class, collectionId)
			.getBody();
	}
```

**Comment by mohamedYoussfi** [comment]
Right.
Is there any update of this issue?

**Comment by markpollack** [comment]
We will be  triaging shortly.

**Comment by arvind-kumar-avinash** [comment]
I am facing a similar issue. I have the following entry in the application.properties file:

```
spring.ai.vectorstore.chroma.initialize-schema=true
spring.ai.vectorstore.chroma.collection-name=demo
```

**Docker command:**

`docker run -it --rm --name chroma -p 8000:8000 ghcr.io/chroma-core/chroma:latest`

**LOG:**

```
INFO:     [19-01-2025 10:56:08] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
WARNING:  [19-01-2025 10:58:19] Unsupported upgrade request.
INFO:     [19-01-2025 10:58:19] 172.17.0.1:42208 - "GET /api/v1/collections/demo HTTP/1.1" 400
```

**Other details:**
```
Java version: 21
Spring Boot version: 3.4.1
spring-ai.version:1.0.0-M4
```
