### ISSUE TITLE
Failed to create bean on TransformersEmbeddingModelAutoConfiguration class

### ISSUE THREAD

**Issue by NineWoranop** [spring-projects/spring-ai#1391]
**Bug description**
I got this error when I create embeddingModel bean during start spring boot application.
2024-09-21T14:46:42.123+07:00  WARN 4944 --- [ollama-example1] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatController' defined in file [C:\git\spring-ai-examples\backend\ollama-example2\target\classes\com\example\demo\rest\ChatController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'chatService' defined in file [C:\git\spring-ai-examples\backend\ollama-example2\target\classes\com\example\demo\service\ChatService.class]: Unsatisfied dependency expressed through constructor parameter 2: Error creating bean with name 'documentLoaderService' defined in file [C:\git\spring-ai-examples\backend\ollama-example2\target\classes\com\example\demo\service\DocumentLoaderService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'vectorStore' defined in class path resource [org/springframework/ai/autoconfigure/vectorstore/chroma/ChromaVectorStoreAutoConfiguration.class]: Unsatisfied dependency expressed through method 'vectorStore' parameter 0: Error creating bean with name 'embeddingModel' defined in class path resource [org/springframework/ai/autoconfigure/transformers/TransformersEmbeddingModelAutoConfiguration.class]: Failed to cache the resource: URL [https://raw.githubusercontent.com/spring-projects/spring-ai/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/tokenizer.json]
2024-09-21T14:46:42.126+07:00  INFO 4944 --- [ollama-example1] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-09-21T14:46:42.144+07:00  INFO 4944 --- [ollama-example1] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-09-21T14:46:42.166+07:00 ERROR 4944 --- [ollama-example1] [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatController' defined in file [C:\git\spring-ai-examples\backend\ollama-example2\target\classes\com\example\demo\rest\ChatController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'chatService' defined in file [C:\git\spring-ai-examples\backend\ollama-example2\target\classes\com\example\demo\service\ChatService.class]: Unsatisfied dependency expressed through constructor parameter 2: Error creating bean with name 'documentLoaderService' defined in file [C:\git\spring-ai-examples\backend\ollama-example2\target\classes\com\example\demo\service\DocumentLoaderService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'vectorStore' defined in class path resource [org/springframework/ai/autoconfigure/vectorstore/chroma/ChromaVectorStoreAutoConfiguration.class]: Unsatisfied dependency expressed through method 'vectorStore' parameter 0: Error creating bean with name 'embeddingModel' defined in class path resource [org/springframework/ai/autoconfigure/transformers/TransformersEmbeddingModelAutoConfiguration.class]: Failed to cache the resource: URL [https://raw.githubusercontent.com/spring-projects/spring-ai/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/tokenizer.json]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1192) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.6.jar:6.1.6]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.6.jar:6.1.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.5.jar:3.2.5]
	at com.example.demo.DemoApplication.main(DemoApplication.java:11) ~[classes/:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'chatService' defined in file 

**Environment**
Spring AI : 1.0.0-M2
Spring Boot: 3.2.5
Java : 17
Local machine that run under company's network that have company's proxy which will block any unknown https to calling out

**Steps to reproduce**
- spring.ai.embedding.transformer.enabled=true
- Run under company's network that have company's proxy which will block any unknown https to calling out

**Expected behavior**
TransformersEmbeddingModelAutoConfiguration should not call this url. 
https://raw.githubusercontent.com/spring-projects/spring-ai/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/tokenizer.json
Due to spring ai application should allow to run under private network that don't need internet.
 
**Minimal Complete Reproducible example**
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-transformers-spring-boot-starter</artifactId>
            <version>1.0.0-M2</version>
        </dependency>

**Comment by inpink** [comment]
Hello, could you share the code that triggered this error when it was executed? I’d like to test it as well :)

**Comment by NineWoranop** [comment]
No java code. I just have pom.xml and application.properties.

**Comment by NineWoranop** [comment]
This is normal logs when it run under normal internet.
2024-09-30T06:06:28.404+07:00  INFO 1116 --- [ollama-example2] [           main] com.example.demo.DemoApplication         : Starting DemoApplication using Java 17.0.11 with PID 1116 (/Users/tom/git/ollama-example2/target/classes started by tom in /Users/tom/git/ollama-example2)
2024-09-30T06:06:28.405+07:00  INFO 1116 --- [ollama-example2] [           main] com.example.demo.DemoApplication         : No active profile set, falling back to 1 default profile: "default"
2024-09-30T06:06:28.964+07:00  INFO 1116 --- [ollama-example2] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-09-30T06:06:28.970+07:00  INFO 1116 --- [ollama-example2] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-09-30T06:06:28.970+07:00  INFO 1116 --- [ollama-example2] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.20]
2024-09-30T06:06:29.014+07:00  INFO 1116 --- [ollama-example2] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-09-30T06:06:29.014+07:00  INFO 1116 --- [ollama-example2] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 584 ms
2024-09-30T06:06:29.415+07:00  INFO 1116 --- [ollama-example2] [           main] o.s.a.transformers.ResourceCacheService  : Create cache root directory: /var/folders/d7/f5vyr_n10hxd9sf_xygdfmyh0000gn/T/spring-ai-onnx-generative
2024-09-30T06:06:30.174+07:00  INFO 1116 --- [ollama-example2] [           main] o.s.a.transformers.ResourceCacheService  : Caching the URL [https://raw.githubusercontent.com/spring-projects/spring-ai/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/tokenizer.json] resource to: /var/folders/d7/f5vyr_n10hxd9sf_xygdfmyh0000gn/T/spring-ai-onnx-generative/4d42ba07-cb22-352f-bb44-beccc8c8c0b7/tokenizer.json
2024-09-30T06:06:34.707+07:00  INFO 1116 --- [ollama-example2] [           main] ai.djl.util.Platform                     : Found matching platform from: jar:file:/Users/tom/.m2/repository/ai/djl/huggingface/tokenizers/0.28.0/tokenizers-0.28.0.jar!/native/lib/tokenizers.properties
2024-09-30T06:06:45.018+07:00  INFO 1116 --- [ollama-example2] [           main] o.s.a.transformers.ResourceCacheService  : Caching the URL [https://github.com/spring-projects/spring-ai/raw/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/model.onnx] resource to: /var/folders/d7/f5vyr_n10hxd9sf_xygdfmyh0000gn/T/spring-ai-onnx-generative/eb4e1bd7-63c5-301b-8383-5df6a4a2adea/model.onnx
2024-09-30T06:06:45.109+07:00  INFO 1116 --- [ollama-example2] [           main] o.s.a.t.TransformersEmbeddingModel       : Model input names: input_ids, attention_mask, token_type_ids
2024-09-30T06:06:45.109+07:00  INFO 1116 --- [ollama-example2] [           main] o.s.a.t.TransformersEmbeddingModel       : Model output names: last_hidden_state
2024-09-30T06:06:45.141+07:00  INFO 1116 --- [ollama-example2] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path ''
2024-09-30T06:06:45.148+07:00  INFO 1116 --- [ollama-example2] [           main] com.example.demo.DemoApplication         : Started DemoApplication in 16.959 seconds (process running for 17.245)

**Comment by NineWoranop** [comment]
This is the error when I turn off my wifi.

2024-09-30T06:31:17.533+07:00  INFO 1043 --- [ollama-example2] [           main] com.example.demo.DemoApplication         : Starting DemoApplication using Java 17.0.11 with PID 1043 (/Users/tom/git/ollama-example2/target/classes started by tom in /Users/tom/git/ollama-example2)
2024-09-30T06:31:17.534+07:00  INFO 1043 --- [ollama-example2] [           main] com.example.demo.DemoApplication         : No active profile set, falling back to 1 default profile: "default"
2024-09-30T06:31:17.999+07:00  INFO 1043 --- [ollama-example2] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-09-30T06:31:18.004+07:00  INFO 1043 --- [ollama-example2] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-09-30T06:31:18.004+07:00  INFO 1043 --- [ollama-example2] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.20]
2024-09-30T06:31:18.037+07:00  INFO 1043 --- [ollama-example2] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-09-30T06:31:18.037+07:00  INFO 1043 --- [ollama-example2] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 481 ms
2024-09-30T06:31:18.408+07:00  INFO 1043 --- [ollama-example2] [           main] o.s.a.transformers.ResourceCacheService  : Create cache root directory: /var/folders/d7/f5vyr_n10hxd9sf_xygdfmyh0000gn/T/spring-ai-onnx-generative
2024-09-30T06:31:18.415+07:00  WARN 1043 --- [ollama-example2] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddingModel' defined in class path resource [org/springframework/ai/autoconfigure/transformers/TransformersEmbeddingModelAutoConfiguration.class]: Failed to cache the resource: URL [https://raw.githubusercontent.com/spring-projects/spring-ai/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/tokenizer.json]
2024-09-30T06:31:18.418+07:00  INFO 1043 --- [ollama-example2] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-09-30T06:31:18.432+07:00  INFO 1043 --- [ollama-example2] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-09-30T06:31:18.441+07:00 ERROR 1043 --- [ollama-example2] [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddingModel' defined in class path resource [org/springframework/ai/autoconfigure/transformers/TransformersEmbeddingModelAutoConfiguration.class]: Failed to cache the resource: URL [https://raw.githubusercontent.com/spring-projects/spring-ai/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/tokenizer.json]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.6.jar:6.1.6]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.6.jar:6.1.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.5.jar:3.2.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.5.jar:3.2.5]
	at com.example.demo.DemoApplication.main(DemoApplication.java:10) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Failed to cache the resource: URL [https://raw.githubusercontent.com/spring-projects/spring-ai/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/tokenizer.json]
	at org.springframework.ai.transformers.ResourceCacheService.getCachedResource(ResourceCacheService.java:116) ~[spring-ai-transformers-1.0.0-M2.jar:1.0.0-M2]
	at org.springframework.ai.transformers.TransformersEmbeddingModel.getCachedResource(TransformersEmbeddingModel.java:209) ~[spring-ai-transformers-1.0.0-M2.jar:1.0.0-M2]
	at org.springframework.ai.transformers.TransformersEmbeddingModel.afterPropertiesSet(TransformersEmbeddingModel.java:182) ~[spring-ai-transformers-1.0.0-M2.jar:1.0.0-M2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-6.1.6.jar:6.1.6]
	... 16 common frames omitted
Caused by: java.net.UnknownHostException: raw.githubusercontent.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[na:na]
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1687) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[na:na]
	at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:232) ~[spring-core-6.1.6.jar:6.1.6]
	at org.springframework.ai.transformers.ResourceCacheService.getCachedResource(ResourceCacheService.java:110) ~[spring-ai-transformers-1.0.0-M2.jar:1.0.0-M2]
	... 20 common frames omitted


Process finished with exit code 1

**Comment by ZYMCao** [comment]
I have the same issue. Did you find out the solution, @NineWoranop ?

**Comment by markpollack** [comment]
so much has changed since this was reported and i'm not sure how to reproduce with the info given.  closing, please open if necessary.
