### ISSUE TITLE
is there doc about function call

### ISSUE THREAD

**Issue by oneanime** [spring-projects/spring-ai#314]
below my application.yml about function calling configuration

chat:
  options:
    model: gpt-4
    tools: getCurrentWeather

And,this is my function:
public String getCurrentWeather(String location) {
        return location + "the weather is good";
    }

but it is not work,this is my log

Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [@com.fasterxml.jackson.annotation.JsonProperty java.util.List<org.springframework.ai.openai.api.OpenAiApi$FunctionTool>]
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:119)
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:101)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.convert(IndexedElementsBinder.java:145)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindValue(IndexedElementsBinder.java:95)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:83)
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:70)
	at org.springframework.boot.context.properties.bind.CollectionBinder.bindAggregate(CollectionBinder.java:48)
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:56)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$4(Binder.java:442)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:597)
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:442)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:403)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:350)
	... 118 more

**Comment by tzolov** [comment]
@oneanime ,
please check the status here: https://github.com/spring-projects/spring-ai/discussions/193#discussioncomment-8428907

**Comment by markpollack** [comment]
Yes, check here https://docs.spring.io/spring-ai/reference/0.8-SNAPSHOT/api/functions.html
