### ISSUE TITLE
'JsonEOFException: Unexpected end-of-input: expected close marker for Object' when making synchronous openAiChatClient.call

### ISSUE THREAD

**Issue by dolukhanov** [spring-projects/spring-ai#372]
**Bug description**
When making a basic synchronous openAiChatClient.call( prompt) with a single UserMessage, an Exception is thrown (com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 1]))

I have inspected the traffic using Charles, and the OpenAI API is returning a correct JSON response. 

**Environment**
Please provide as many details as possible: Spring AI version, Java version, which vector store you use if any, etc
OpenJDK 18.0.2
Spring Framework 6.1.4
Spring Boot 3.2.3
Spring Open AI 0.8.0-SNAPSHOT

**Steps to reproduce**
Basic synchronous call 

`String message = "Tell me about OpenAI";

        UserMessage userMessage = new UserMessage( message );
        List<Message> openAiMessages = List.of( userMessage );
        Prompt prompt = new Prompt( openAiMessages );
        ChatResponse call = openAiChatClient.call( prompt );
        Generation generation = call.getResults().get( 0 );
        System.out.println( generation.getOutput().getContent() );
`

**Expected behavior**
Chat response is printed.

**Stack Trace**
`Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 1])

	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:406) ~[spring-web-6.1.4.jar:6.1.4]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354) ~[spring-web-6.1.4.jar:6.1.4]
	at org.springframework.web.client.DefaultRestClient.readWithMessageConverters(DefaultRestClient.java:213) ~[spring-web-6.1.4.jar:6.1.4]
	... 82 common frames omitted
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 1])
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:697) ~[jackson-core-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:512) ~[jackson-core-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:529) ~[jackson-core-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3103) ~[jackson-core-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:757) ~[jackson-core-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:181) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481) ~[jackson-databind-2.15.4.jar:2.15.4]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:395) ~[spring-web-6.1.4.jar:6.1.4]
	... 84 common frames omitted`

**Comment by carlspring** [comment]
I am experiencing the same issue.

**Comment by vwiencek** [comment]
I have the same problem and can't figure out how to solve it

**Comment by jocax** [comment]
I had the same issue and found a workaround by setting the required http header "Accept-Encoding". I applied the header in the Rest.Builder. One the header is set the response can be read without the above error.

    @Bean
    RestClient.Builder restClientBuilder() {
        return RestClient.builder()
                .defaultHeaders(new Consumer<HttpHeaders>() {
                    @Override
                    public void accept(HttpHeaders httpHeaders) {
                        // https://github.com/spring-projects/spring-ai/issues/372
                        httpHeaders.set("Accept-Encoding", "gzip, deflate");
                    }
                });
    }

Hope this helps.

**Comment by ThomasVitale** [comment]
Spring Boot provides an autoconfigured `RestClient.Builder` object, including JSON serialization configuration. Have you tried using that one instead of defining one yourself?

When you create a `RestClient` via `RestClient.builder()`, you don't get the Spring Boot autoconfiguration, so it's up to you to configure encoding and serialization. If you create one from an autowired `RestClient.Builder` bean, that is all configured for you and should work out-of-the-box.

**Comment by Alien2150** [comment]
So my workaround that is not that super invasive as overwritting the default RestClient builder:

```
    @Bean
    fun chatModel(
        commonProperties: OpenAiConnectionProperties,
        chatProperties: OpenAiChatProperties,
        webClientBuilder: WebClient.Builder,
        retryTemplate: RetryTemplate,
        functionCallbackContext: FunctionCallbackContext,
        responseErrorHandler: ResponseErrorHandler,
    ): OpenAiChatModel {
        val restClientBuilder = RestClient.builder().defaultHeaders {
            it.set(HttpHeaders.ACCEPT_ENCODING, "gzip, deflate")
        }

        val openAiApi = OpenAiApi(
            chatProperties.baseUrl ?: commonProperties.baseUrl,
            chatProperties.apiKey ?: commonProperties.apiKey,
            restClientBuilder,
            webClientBuilder,
            responseErrorHandler,
        )

        return OpenAiChatModel(
            openAiApi,
            chatProperties.options,
            functionCallbackContext,
            retryTemplate,
        )
    }
```

**Comment by markpollack** [comment]
I was thining the same thing @Alien2150 in relation to setting timeouts per model, using a qualifier annotation that will pick up a specific restClientBuilder.  It would seem that this problem would have been solved already with apps calling many microservices, each with different time outs...  https://github.com/spring-projects/spring-ai/issues/512 and related issues discuss it more.

**Comment by hebertsouza87** [comment]
a had the same problem, a sove removing all imports of httpclient5 (in my case, it was on spring-cloud-starter-config)

**Comment by coderphonui** [comment]
> So my workaround that is not that invasive as overwritting the default RestClient builder:
> 
> ```
>     @Bean
>     fun chatModel(
>         commonProperties: OpenAiConnectionProperties,
>         chatProperties: OpenAiChatProperties,
>         webClientBuilder: WebClient.Builder,
>         retryTemplate: RetryTemplate,
>         functionCallbackContext: FunctionCallbackContext,
>         responseErrorHandler: ResponseErrorHandler,
>     ): OpenAiChatModel {
>         val restClientBuilder = RestClient.builder().defaultHeaders {
>             it.set(HttpHeaders.ACCEPT_ENCODING, "gzip, deflate")
>         }
> 
>         val openAiApi = OpenAiApi(
>             chatProperties.baseUrl ?: commonProperties.baseUrl,
>             chatProperties.apiKey ?: commonProperties.apiKey,
>             restClientBuilder,
>             webClientBuilder,
>             responseErrorHandler,
>         )
> 
>         return OpenAiChatModel(
>             openAiApi,
>             chatProperties.options,
>             functionCallbackContext,
>             retryTemplate,
>         )
>     }
> ```
> 
> As a suggestion: Could the bean for RestClient builder not use a "Qualifier" annotation so it would not be overwritten by the default one? (OpenAiAutoConfiguration seems to use the default one)

Adding the httpHeaders.set("Accept-Encoding", "gzip, deflate"); fixed the issue.  Thanks!

**Comment by asw12** [comment]
I encountered and researched this defect a bit further out of curiosity, and found the culprit to be brotli decompression support, hence why using an Accept-Encoding that excludes "br" avoids the problem.

The dependency tree bringing in brotli looks something like:
```
[INFO] |  +- org.springframework.ai:spring-ai-tika-document-reader:jar:1.0.0-M6:compile
                  ...
[INFO] |  |     +- org.apache.tika:tika-parser-pkg-module:jar:3.0.0:compile
[INFO] |  |     |  +- org.brotli:dec:jar:0.1.2:compile
```
where that brotli dec-0.1.2.jar was a version that was last published [to Maven Central by Google 7 years ago](https://central.sonatype.com/artifact/org.brotli/dec/versions).

There is an issue with BrotliInputStream in that library when they read from an internal buffer without depleting it, that the read method incorrectly reports a -1 value signifying an EOF. There appears to be a [fix in later versions](https://github.com/google/brotli/commit/a8f5813b843b7ec469dbd3d8a6a8743395359964#diff-be71ac0606ccc6f8a0a1bb56b63c9c57e3db7cfe2f7113080e74cb2e1fe9d02cL154), but even though this fix was committed 3 years ago, they never published it.

So the problem looks like
* Jackson does a preliminary check to see if the body has content by calling read() for one byte.
  * BrotliInputStream populates the buffer with ~8kb worth of data. '{' is read from it.
  * That character is "unread" back to a buffer held by a wrapping PushbackInputStream
* Jackson tries to parse JSON from the InputStream with its parser.
  * The '{' is read back, followed by some hundreds of bytes, but not enough to cause BrotliInputStream's buffer to be depleted.
  * BrotliInputStream reports -1 for the read call, so Jackson only sees a START_OBJECT before an unexpected JsonEOFException is thrown.

**Comment by soheilrahsaz** [comment]
Yes, in fact, removing `spring-ai-tika-document-reader` dependency fixes this issue.  This problem still exists in version 1.1.0-M4.

**Comment by aalamu** [comment]
@soheilrahsaz I was also using `spring-ai-tika-document-reader` and then ChatGPT suggested

```
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-tika-document-reader</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.brotli</groupId>
                    <artifactId>dec</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

This worked for me and I didn't have to change my rest client configuration.

**Comment by sdeleuze** [comment]
I think it has been fixed in Spring Boot 4 and Spring AI 2, if not please comment.
