### ISSUE TITLE
Error creating bean with name 'retryTemplate' defined in class path resource [org/springframework/ai/autoconfigure/retry/SpringAiRetryAutoConfiguration.class]:

### ISSUE THREAD

**Issue by Jeffrey-Dozva** [spring-projects/spring-ai#546]
**Bug description**
When i try run my code this is the error thats returned
`
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retryTemplate' defined in class path resource [org/springframework/ai/autoconfigure/retry/SpringAiRetryAutoConfiguration.class]: Failed to instantiate [org.springframework.retry.support.RetryTemplate]: Factory method 'retryTemplate' threw exception with message: org/springframework/ai/retry/NonTransientAiException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941) ~[spring-context-6.0.9.jar:6.0.9]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.9.jar:6.0.9]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[spring-boot-3.1.0.jar:3.1.0]
	at com.wellbayt.engine.EngineApplicationKt.main(EngineApplication.kt:81) ~[main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.retry.support.RetryTemplate]: Factory method 'retryTemplate' threw exception with message: org/springframework/ai/retry/NonTransientAiException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.9.jar:6.0.9]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.9.jar:6.0.9]
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/ai/retry/NonTransientAiException
	at org.springframework.ai.autoconfigure.retry.SpringAiRetryAutoConfiguration.retryTemplate(SpringAiRetryAutoConfiguration.java:55) ~[spring-ai-spring-boot-autoconfigure-0.8.1-SNAPSHOT.jar:0.8.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.9.jar:6.0.9]
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.ai.retry.NonTransientAiException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
	... 26 common frames omitted

Process finished with exit code 1

`

**Environment**
Java: 17
Springboot: 3.1.0
`
dependencyManagement {
	imports {
		mavenBom("org.springframework.ai:spring-ai-bom:0.8.1-SNAPSHOT")
	}
}
dependencies {
	implementation("org.springframework.ai:spring-ai-azure-openai-spring-boot-starter")
}
`

**Steps to reproduce**
When I start my springboot application it crashes with the error above
When i send a simple promp for openai to respond with yes if its ready to assist. it returns yes. This means my configuration is okay and i can call the model

**Expected behavior**
Application cannot start up. It crashes

**Minimal Complete Reproducible example**
Please provide a failing test or a minimal complete verifiable example that reproduces the issue.
Bug reports that are reproducible will take priority in resolution over reports that are not reproducible.

**Comment by shashikanth-gs** [comment]
@Jeffrey-Dozva, looks like a bug in pom. a transitive dependency is not pulled in. Providing the below dependency resolved the issue for me. 
<dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-retry</artifactId>
            <version>0.8.1-SNAPSHOT</version>
</dependency>

**Comment by Jeffrey-Dozva** [comment]
@shashikanth-gs 

after adding the above library getting this error

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.ai.autoconfigure.retry.SpringAiRetryAutoConfiguration.retryTemplate(SpringAiRetryAutoConfiguration.java:57)

The following method did not exist:

    'org.springframework.retry.support.RetryTemplateBuilder org.springframework.retry.support.RetryTemplateBuilder.exponentialBackoff(java.time.Duration, double, java.time.Duration)'

The calling method's class, org.springframework.ai.autoconfigure.retry.SpringAiRetryAutoConfiguration, was loaded from the following location:

    jar:file:/Users/jeffrey/.gradle/caches/modules-2/files-2.1/org.springframework.ai/spring-ai-spring-boot-autoconfigure/0.8.1-SNAPSHOT/82c1746defff35f7705490b0ecf36d9fde569755/spring-ai-spring-boot-autoconfigure-0.8.1-SNAPSHOT.jar!/org/springframework/ai/autoconfigure/retry/SpringAiRetryAutoConfiguration.class

The called method's class, org.springframework.retry.support.RetryTemplateBuilder, is available from the following locations:

    jar:file:/Users/jeffrey/.gradle/caches/modules-2/files-2.1/org.springframework.retry/spring-retry/2.0.1/7251dcd778aa5338f0866bf8cfbb80f3f2058d97/spring-retry-2.0.1.jar!/org/springframework/retry/support/RetryTemplateBuilder.class

The called method's class hierarchy was loaded from the following locations:

    org.springframework.retry.support.RetryTemplateBuilder: file:/Users/jeffrey/.gradle/caches/modules-2/files-2.1/org.springframework.retry/spring-retry/2.0.1/7251dcd778aa5338f0866bf8cfbb80f3f2058d97/spring-retry-2.0.1.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.ai.autoconfigure.retry.SpringAiRetryAutoConfiguration and org.springframework.retry.support.RetryTemplateBuilder


Process finished with exit code 1

**Comment by rajadilipkolli** [comment]
`spring-ai-ollama-spring-boot-starter` also has similar issue, whereas `spring-ai-openai-spring-boot-starter` has first class support for this. Perhaps should visit all starters once for retry

**Comment by tzolov** [comment]
Hi @Jeffrey-Dozva , I'm afraid that Boot 3.1.x does not support the [RestClient](https://docs.spring.io/spring-framework/reference/integration/rest-clients.html#rest-restclient) library used internally by Spring AI.
Please,  update to Spring Boot 3.2.x better (3.2.4) and let me know if this issue is still present.

**Comment by faruzanCN** [comment]
> Hi @Jeffrey-Dozva , I'm afraid that Boot 3.1.x does not support the [RestClient](https://docs.spring.io/spring-framework/reference/integration/rest-clients.html#rest-restclient) library used internally by Spring AI. Please, update to Spring Boot 3.2.x better (3.2.4) and let me know if this issue is still present.


When I use spring-ai-ollama-spring-boot-starter, an exception occurs: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retryTemplate' defined in class path resource [org/springframework/ai/autoconfigure/retry/SpringAiRetryAutoConfiguration.class]: Failed to instantiate [org.springframework.retry.support.RetryTemplate]: Factory method 'retryTemplate' threw exception with message: org/springframework/ai/retry/NonTransientAiException.
My Springboot version is 3.2.4, spring-ai-bom version is 0.8.1-SNAPSHOT.


org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retryTemplate' defined in class path resource [org/springframework/ai/autoconfigure/retry/SpringAiRetryAutoConfiguration.class]: Failed to instantiate [org.springframework.retry.support.RetryTemplate]: Factory method 'retryTemplate' threw exception with message: org/springframework/ai/retry/NonTransientAiException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1335) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1165) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.4.jar:3.2.4]
	at com.luvletter.faruzanserver.FaruzanServerApplication.main(FaruzanServerApplication.java:16) ~[classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.retry.support.RetryTemplate]: Factory method 'retryTemplate' threw exception with message: org/springframework/ai/retry/NonTransientAiException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.5.jar:6.1.5]
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/ai/retry/NonTransientAiException
	at org.springframework.ai.autoconfigure.retry.SpringAiRetryAutoConfiguration.retryTemplate(SpringAiRetryAutoConfiguration.java:55) ~[spring-ai-spring-boot-autoconfigure-0.8.1-20240312.174040-75.jar:0.8.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140) ~[spring-beans-6.1.5.jar:6.1.5]
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.ai.retry.NonTransientAiException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
	... 26 common frames omitted

**Comment by tzolov** [comment]
Thanks for the clarification @Jeffrey-Dozva , but please switch to `1.0.0-SNAPSHOT`.  I know it is strange but the continuation after the 0.8.1 milestone will be 1.0.0-M1 milestone and the 1.0.0-SNAPSHOT is the snapshot in between.  The 0.8.1-SNAPSHOT is invalid or at best the same as 0.8.1

**Comment by walidhsn** [comment]
i had the same problem idk why , first i worked  on a project to test the rest api before implementing them in my initial project , i just select azure open ai and spring web ,and spring developer tools , and everything works fine , until i wanted to implement the spring ai in my actual project i had the same pb you had ,even i tried to start another project with the same steps i did before and add my actual project old dependencies the same error appears this time so i canceled that. and return to my own project trying again until i saw the solution of @shashikanth-gs , so i gave it a try and it works :
```              <dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-retry</artifactId>
		</dependency>```

**Comment by walidhsn** [comment]
i had the same problem idk why , first i worked on a project to test the rest api before implementing them in my initial project , i just select azure open ai and spring web ,and spring developer tools , and everything works fine , until i wanted to implement the spring ai in my actual project i had the same pb you had ,even i tried to start another project with the same steps i did before and add my actual project old dependencies the same error appears this time so i canceled that. and return to my own project trying again until i saw the solution of @shashikanth-gs , so i gave it a try and it works :
```

<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-retry</artifactId>
		</dependency>

```
