### ISSUE TITLE
choices()" is null

### ISSUE THREAD

**Issue by leo07051004** [spring-projects/spring-ai#690]
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.springframework.ai.openai.api.OpenAiApi$ChatCompletion.choices()" is null
	at org.springframework.ai.openai.OpenAiChatClient.lambda$call$1(OpenAiChatClient.java:153)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:335)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:211)
	at org.springframework.ai.openai.OpenAiChatClient.call(OpenAiChatClient.java:141)

<dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-openai-spring-boot-starter</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

**Comment by markpollack** [comment]
Closing as is fixed in  a77d11c
